import { useEffect } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useAuthStore } from '../../store/authStore';
import { useLocationStore } from '../../store/locationStore';
import { LocationMapCard } from '../../components/location/LocationMapCard';
import { safeTrackColors as colors, safeTrackSpacing as spacing } from '../../constants/safeTrackDesign';

export default function LocationScreen(){
 const role=useAuthStore(s=>s.role);const child=useAuthStore(s=>s.child);const children=useAuthStore(s=>s.linkedChildren);const primary=role==='child'?child:children[0];const location=useLocationStore(s=>s.latest);const loading=useLocationStore(s=>s.isLoading);const load=useLocationStore(s=>s.loadForChild);useEffect(()=>{if(primary?.id)void load(primary.id)},[primary?.id]);
 return <SafeAreaView style={styles.safe} edges={['top','left','right']}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><View><Text style={styles.eyebrow}>LOCATION TRACKING</Text><Text style={styles.heading}>{primary?.fullName||'Child'}&apos;s location</Text><Text style={styles.subtitle}>Pinch, zoom, and move around the map to review the latest available record.</Text></View><Pressable onPress={()=>primary?.id&&void load(primary.id)} style={({pressed})=>[styles.action,pressed&&styles.pressed]}><Ionicons name={loading?'sync-outline':'refresh-outline'} size={21} color={colors.primaryDark}/></Pressable></View><LocationMapCard location={location} height={510} loading={loading} onRefresh={()=>primary?.id&&void load(primary.id)}/><View style={styles.note}><View style={styles.info}><Text style={styles.infoText}>i</Text></View><Text style={styles.noteText}>{location?'The marker represents the latest location successfully received and stored by SafeTrack.':'A marker appears after the paired child device sends and stores a location record.'}</Text></View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{paddingHorizontal:spacing.lg,paddingTop:35,paddingBottom:35},header:{flexDirection:'row',justifyContent:'space-between',marginBottom:18},eyebrow:{color:colors.primary,fontSize:10.5,fontWeight:'900',letterSpacing:1.4},heading:{color:colors.ink,fontSize:27,fontWeight:'900',marginTop:6,letterSpacing:-.6},subtitle:{color:colors.muted,fontSize:12.5,lineHeight:18,marginTop:4,maxWidth:280},action:{width:43,height:43,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:colors.softMint,marginLeft:12},note:{flexDirection:'row',alignItems:'flex-start',marginTop:16,paddingHorizontal:2},info:{width:20,height:20,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:colors.softMint},infoText:{color:colors.primaryDark,fontSize:12,fontWeight:'900'},noteText:{flex:1,color:colors.muted,fontSize:12.5,lineHeight:18,marginLeft:9},pressed:{opacity:.72}});
