import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system/legacy";
import type { AdminReportSummary } from "./adminService";

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function escapeCsv(value: string | number) {
  return `"${String(value).replaceAll('"', '""')}"`;
}

function formatRange(startDate: string, endDate: string) {
  const formatter = new Intl.DateTimeFormat("en-PH", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });

  return `${formatter.format(
    new Date(`${startDate}T12:00:00`)
  )} to ${formatter.format(new Date(`${endDate}T12:00:00`))}`;
}

function getRows(summary: AdminReportSummary) {
  return [
    ["Guardian Accounts", summary.guardianAccounts],
    ["Registered Children", summary.registeredChildren],
    ["Smartwatch Devices", summary.smartwatchDevices],
    ["Location Records", summary.locationRecords],
    ["Safe-Zone Events", summary.safeZoneEvents],
    ["SOS Records", summary.sosRecords],
  ] as const;
}

async function shareFile(
  uri: string,
  mimeType: string,
  title: string
) {
  const canShare = await Sharing.isAvailableAsync();

  if (!canShare) {
    throw new Error("File sharing is unavailable on this device.");
  }

  await Sharing.shareAsync(uri, {
    mimeType,
    dialogTitle: title,
  });
}

export async function exportAdminSummaryPdf(
  summary: AdminReportSummary,
  startDate: string,
  endDate: string
) {
  const range = formatRange(startDate, endDate);

  const rows = getRows(summary)
    .map(
      ([label, value]) => `
        <tr>
          <td>${escapeHtml(label)}</td>
          <td>${escapeHtml(String(value))}</td>
        </tr>
      `
    )
    .join("");

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8" />
        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 28px;
            color: #10291C;
          }

          h1 {
            margin: 0;
            color: #117447;
            font-size: 25px;
          }

          h2 {
            margin-top: 8px;
            color: #66766E;
            font-size: 13px;
            font-weight: normal;
          }

          .notice {
            margin-top: 22px;
            padding: 16px;
            border-radius: 14px;
            background: #EAF8F0;
            color: #32654A;
            font-size: 12px;
            line-height: 1.5;
          }

          table {
            width: 100%;
            margin-top: 22px;
            border-collapse: collapse;
          }

          th {
            text-align: left;
            background: #117447;
            color: #FFFFFF;
            padding: 11px;
            font-size: 12px;
          }

          td {
            padding: 11px;
            border-bottom: 1px solid #DCEAE1;
            font-size: 12px;
          }

          td:last-child {
            text-align: right;
            font-weight: bold;
          }

          .footer {
            margin-top: 25px;
            color: #7A8A82;
            font-size: 10px;
          }
        </style>
      </head>

      <body>
        <h1>SafeTrack Administrative Summary</h1>
        <h2>Selected period: ${escapeHtml(range)}</h2>

        <div class="notice">
          This report summarizes successfully stored administrative records.
          It does not confirm a child’s safety condition or emergency status.
        </div>

        <table>
          <thead>
            <tr>
              <th>Record Type</th>
              <th>Total</th>
            </tr>
          </thead>

          <tbody>
            ${rows}
          </tbody>
        </table>

        <p class="footer">
          Generated by the SafeTrack Mobile Administrator Module.
        </p>
      </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({
    html,
  });

  await shareFile(
    uri,
    "application/pdf",
    "Export SafeTrack PDF Summary"
  );
}

export async function exportAdminSummaryCsv(
  summary: AdminReportSummary,
  startDate: string,
  endDate: string
) {
  const cacheDirectory = FileSystem.cacheDirectory;

  if (!cacheDirectory) {
    throw new Error("SafeTrack could not access temporary file storage.");
  }

  const rows = [
    ["SafeTrack Administrative Summary"],
    [`Selected Period: ${formatRange(startDate, endDate)}`],
    [],
    ["Record Type", "Total"],
    ...getRows(summary),
  ];

  const csv = rows
    .map((row) => row.map((value) => escapeCsv(value)).join(","))
    .join("\n");

  const filename = `SafeTrack_Admin_Report_${startDate.replaceAll(
    "-",
    ""
  )}_${endDate.replaceAll("-", "")}.csv`;

  const uri = `${cacheDirectory}${filename}`;

  await FileSystem.writeAsStringAsync(uri, csv, {
    encoding: FileSystem.EncodingType.UTF8,
  });

  await shareFile(
    uri,
    "text/csv",
    "Export SafeTrack Excel-Compatible CSV"
  );
}